TrajectoryPlannerROS:
  publish_cost_grid_pc: true
  dwa: false

  holonomic_robot: false
  sim_time: 5
  #
  # yaw_goal_tolerance: 0.1
  # xy_goal_tolerance: 0.2
  meter_scoring: true
  pdist_scale: 0.6
  # gdist_scale: 0.2
  # heading_scoring: true
  # heading_lookahead: 0.5
  # heading_scoring_timestep: 1.2
  # max_vel_x: 2.0
  # min_vel_x: -2.0
  # max_vel_theta: 2.0
  # min_vel_theta: -2.0
  # min_in_place_vel_theta: 0.02
